name: gcg
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.binstar.org/tlatorre 
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
dependencies:
    - python==3.5.2
    - numpy==1.11.2
    - scipy==0.18.1
    - path.py==10.3.1
    - python-dateutil==2.6.0
    - joblib==0.9.4
    - mako==1.0.6
    - ipywidgets==5.1.5
    - numba==0.32.0
    - flask==0.12.1
    - pybox2d==2.3.1post2
    - pygame==1.9.2a0
    - h5py==2.7.0
    - matplotlib==2.0.0
    - opencv3=3.1.0
    - scikit-learn==0.18.1
    - pytorch==0.1.12
    - torchvision==0.1.8
    - pip:
        - Pillow==3.4.2
        - atari-py==0.0.21
        - pyprind==2.11.0
        - ipdb==0.10.3
        - boto3==1.4.4
        - PyOpenGL==3.1.0
        - nose2==0.6.5
        - pyzmq==16.0.2
        - msgpack-python==0.4.8
        - mujoco_py==0.5.7
        - cached_property==1.3.0
        - line_profiler==2.0
        - cloudpickle==0.2.2
        - Cython==0.25.2
        - redis==2.10.5
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - awscli==1.11.82
        - git+https://github.com/openai/gym.git@385a85fd0c1b26ab1374f208fbb370e22647548d#egg=gym
        - pyglet==1.2.4
        - jupyter==1.0.0
        - progressbar2==3.18.1
        - chainer==1.18.0
        - tensorflow-gpu==1.2.1
